---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
    tags: ['*.*.*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-check

      - run: cargo check --all

  binary:
    name: Binary
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-${{ matrix.target }}

      - run: cargo install cross --locked
      - run: cross build --target ${{ matrix.target }} --release
      - run: mv target/${{ matrix.target }}/release/moco target/${{ matrix.target }}/release/moco-${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: moco
          path: target/${{ matrix.target }}/release/moco-*

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs:
      - binary
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-xtask

      - uses: actions/download-artifact@v3
        with:
          name: moco
          path: /tmp/artifacts

      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/moco
          tags: |
            type=raw,value=latest,suffix=${{ env.SUFFIX }},enable={{is_default_branch}}
            type=ref,event=pr,suffix=${{ env.SUFFIX }}
            type=ref,event=branch,suffix=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=${{ env.SUFFIX }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ env.SUFFIX }}
            type=semver,pattern={{major}},suffix=${{ env.SUFFIX }}
            type=sha,suffix=${{ env.SUFFIX }}

      - run: cargo xtask build-image
        env:
          # TODO: pull these from a build matrix
          TARGETS: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf

          BINARY_PATH: /tmp/artifacts/moco-{{target}}
          MANIFEST: ${{ github.repository_owner }}/moco:${{ github.sha }}
          TRANSPORT: docker
