---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
    tags: ['*.*.*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-check

      - run: cargo check

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        target:
          - gnu
          - musl
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: matrix.target != 'gnu'
        run: echo 'SUFFIX=-${{ matrix.target }}' >> "$GITHUB_ENV"

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/moco
          tags: |
            type=raw,value=latest,suffix=${{ env.SUFFIX }},enable={{is_default_branch}}
            type=ref,event=pr,suffix=${{ env.SUFFIX }}
            type=ref,event=branch,suffix=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=${{ env.SUFFIX }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ env.SUFFIX }}
            type=semver,pattern={{major}},suffix=${{ env.SUFFIX }}
            type=sha,suffix=${{ env.SUFFIX }}

      - uses: docker/build-push-action@v4
        with:
          file: Dockerfile.${{ matrix.target }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-${{ matrix.target }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.target }}

  binary:
    name: Binary
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-${{ matrix.target }}

      - run: cargo install cross --locked
      - run: cross build --target ${{ matrix.target }} --release

      - uses: actions/upload-artifact@v3
        with:
          name: moco-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/moco
