---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
    tags: ['*.*.*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-check

      - run: cargo check

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update podman and buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah podman

      - run: podman version
        continue-on-error: true
      - run: buildah version
        continue-on-error: true

  binary:
    name: Binary
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-${{ matrix.target }}

      - run: cargo install cross --locked
      - run: cross build --target ${{ matrix.target }} --release
      - run: mv target/${{ matrix.target }}/release/moco target/${{ matrix.target }}/release/moco-${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: moco
          path: target/${{ matrix.target }}/release/moco-*
